export {
  WMT,
  open,
  httpSource,
  bytesSource,
  type ByteSource,
  type WMTSource,
  type OpenOptions,
  type BBox,
  type ZoomRange,
  type ValueRange,
  type Variable,
  type TimeRef,
  type TimeAxis,
  type TileCoord,
  type CoalesceOptions,
  type TileRequest,
  type TilesRequest,
  type SampleRequest,
  type ForecastRequest,
  type ForecastResult,
  type ValueRequest,
  type ValueResult,
} from "./reader.js";

export {
  WMTError,
  FormatError,
  SourceError,
  UnknownVariableError,
  TimeOutOfRangeError,
} from "./errors.js";

export { latLonToTilePixel, type TilePixel } from "./tileid.js";

export { registerLayerBackend } from "./layers.js";
export type {
  WMTLayer,
  WMTHeatmapLayer,
  WMTParticlesLayer,
  WMTIsobarLayer,
  WMTArrowsLayer,
  WMTSymbolLayer,
  WMTHatchLayer,
  HeatmapLayerOptions,
  ParticlesLayerOptions,
  IsobarLayerOptions,
  ArrowsLayerOptions,
  SymbolLayerOptions,
  HatchLayerOptions,
  LayerBackend,
  LayerBackendName,
  BackendLayer,
  LayerKind,
  HeatmapRendererOptions,
  HeatmapRendererState,
  ParticlesRendererOptions,
  ParticlesRendererState,
  IsobarRendererOptions,
  IsobarRendererState,
  ArrowsRendererOptions,
  ArrowsRendererState,
  SymbolRendererOptions,
  SymbolRendererState,
  HatchRendererOptions,
  HatchRendererState,
  HatchBand,
  HatchPatternBand,
  HatchIconBand,
  HatchPattern,
  GlyphSprite,
  SpriteSheet,
  SpriteIcons,
} from "./layers.js";

// Opt-in instrumentation. setDebugSink(fn) starts receiving phase-timed
// events; setDebugSink(null) disables.
export {
  setDebugSink,
  type DebugEvent,
  type DebugSink,
  type ReadEvent,
  type TileEvent,
  type TilesEvent,
  type OpenEvent,
} from "./debug.js";
